services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.production
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    restart: always
    env_file:
      - ./backend/.env.production
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    restart: always
    env_file:
      - ./backend/.env.production
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

volumes:
  db_data:

